// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UMS.Data;

namespace UMS.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220218020557_DatabaseCreated")]
    partial class DatabaseCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "c91e2715-f6d1-4865-9c91-48210911fbba",
                            ConcurrencyStamp = "a4e6eba2-43c4-4e7c-8a4b-56ecd846cfd0",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "3d4dc1f7-1b8d-46de-8904-1143669bb93c",
                            ConcurrencyStamp = "93f89d31-92fb-4c7d-99a6-9b8735b7dfea",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "7452daaf-ebe8-49c1-a1ee-59e65ca6f54f",
                            ConcurrencyStamp = "b5bee6c2-f327-4cbe-96ae-2df66d3e0fc8",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "01a43ed8-1651-4bc4-b3f4-97a22307251f",
                            RoleId = "3d4dc1f7-1b8d-46de-8904-1143669bb93c"
                        },
                        new
                        {
                            UserId = "b3c91fd5-bac2-4ec9-a049-fa4a9a2014e1",
                            RoleId = "7452daaf-ebe8-49c1-a1ee-59e65ca6f54f"
                        },
                        new
                        {
                            UserId = "1c3b39f2-60d8-4eb0-8bfc-8c988f97fa7c",
                            RoleId = "c91e2715-f6d1-4865-9c91-48210911fbba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("UMS.Data.ApiUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "1c3b39f2-60d8-4eb0-8bfc-8c988f97fa7c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "333a346a-7f53-4bb9-b14c-87d1dc998974",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@example.com",
                            EmailConfirmed = false,
                            FirstName = "John",
                            LastName = "Carter",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN@EXAMPLE.COM",
                            NormalizedUserName = "JOHN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECpct+Zio/BMswR5aZaUKVaV/BYc+pYMBDQ9t+62OOAmmiaDp0YKOq0TpGoNEDIWWA==",
                            PhoneNumber = "0772556545",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "98980429-5a60-4633-8a67-0fb0bb114822",
                            TwoFactorEnabled = false,
                            UserName = "john@example.com"
                        },
                        new
                        {
                            Id = "b3c91fd5-bac2-4ec9-a049-fa4a9a2014e1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1299605d-b66f-4169-8c99-512b2c5d0d31",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kate@example.com",
                            EmailConfirmed = false,
                            FirstName = "Kate",
                            LastName = "Jones",
                            LockoutEnabled = false,
                            NormalizedEmail = "KATE@EXAMPLE.COM",
                            NormalizedUserName = "KATE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJUiExrXa0pq95kEnHcA9fTu68uXCQQ2CukCTWRxMf4UC0ry7AetOoZIzNQXV2LJwg==",
                            PhoneNumber = "0712778595",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "83ff1308-bdb9-4867-a10e-5b6a845018cf",
                            TwoFactorEnabled = false,
                            UserName = "kate@example.com"
                        },
                        new
                        {
                            Id = "01a43ed8-1651-4bc4-b3f4-97a22307251f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "98ba1e3e-9e82-489d-9b97-81c110240e53",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sam@example.com",
                            EmailConfirmed = false,
                            FirstName = "Sam",
                            LastName = "Peterson",
                            LockoutEnabled = false,
                            NormalizedEmail = "SAM@EXAMPLE.COM",
                            NormalizedUserName = "SAM@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEL8GE9vfvdK1pzX6A230cx3IegTWeysQoxs+1lcQd4gd1g/jXW+3nHJaXOGpUkJ1Pg==",
                            PhoneNumber = "0751223565",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f10e77fe-7f06-4890-9d44-869387f311f7",
                            TwoFactorEnabled = false,
                            UserName = "sam@example.com"
                        });
                });

            modelBuilder.Entity("UMS.Data.LeaveAllocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("REAL");

                    b.Property<double>("UsedAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveAllocations");

                    b.HasData(
                        new
                        {
                            Id = "5a705d4b-0409-4403-9c38-0c9cd8585611",
                            TotalAmount = 20.0,
                            UsedAmount = 1.0,
                            UserId = "b3c91fd5-bac2-4ec9-a049-fa4a9a2014e1",
                            Year = "2022"
                        });
                });

            modelBuilder.Entity("UMS.Data.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaveStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeaveStatusId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            End = new DateTime(2022, 2, 19, 7, 35, 57, 461, DateTimeKind.Local).AddTicks(7494),
                            LeaveStatusId = 1,
                            LeaveTypeId = 1,
                            Note = "I am down with fever.",
                            Remarks = "Approved",
                            Start = new DateTime(2022, 2, 18, 7, 35, 57, 459, DateTimeKind.Local).AddTicks(9401),
                            UserId = "b3c91fd5-bac2-4ec9-a049-fa4a9a2014e1"
                        },
                        new
                        {
                            Id = 2,
                            End = new DateTime(2022, 3, 5, 7, 35, 57, 461, DateTimeKind.Local).AddTicks(9425),
                            LeaveStatusId = 2,
                            LeaveTypeId = 3,
                            Note = "I am going on a trip to Maldives",
                            Remarks = "Denied",
                            Start = new DateTime(2022, 3, 30, 7, 35, 57, 461, DateTimeKind.Local).AddTicks(9414),
                            UserId = "b3c91fd5-bac2-4ec9-a049-fa4a9a2014e1"
                        },
                        new
                        {
                            Id = 3,
                            End = new DateTime(2022, 2, 20, 7, 35, 57, 461, DateTimeKind.Local).AddTicks(9430),
                            LeaveStatusId = 3,
                            LeaveTypeId = 2,
                            Note = "Need couple of day off for personal reasons",
                            Remarks = "Approved",
                            Start = new DateTime(2022, 2, 23, 7, 35, 57, 461, DateTimeKind.Local).AddTicks(9429),
                            UserId = "b3c91fd5-bac2-4ec9-a049-fa4a9a2014e1"
                        });
                });

            modelBuilder.Entity("UMS.Data.LeaveStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LeaveStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Denied"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pending"
                        });
                });

            modelBuilder.Entity("UMS.Data.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sick Leave"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Personal Leave"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vacation Leave"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UMS.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UMS.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMS.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UMS.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UMS.Data.LeaveAllocation", b =>
                {
                    b.HasOne("UMS.Data.ApiUser", "ApiUser")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ApiUser");
                });

            modelBuilder.Entity("UMS.Data.LeaveRequest", b =>
                {
                    b.HasOne("UMS.Data.LeaveStatus", "LeaveStatus")
                        .WithMany()
                        .HasForeignKey("LeaveStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMS.Data.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UMS.Data.ApiUser", "ApiUser")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ApiUser");

                    b.Navigation("LeaveStatus");

                    b.Navigation("LeaveType");
                });
#pragma warning restore 612, 618
        }
    }
}
